### ISSUE TITLE
App Does Not Compile

### ISSUE THREAD

**Issue by codingjeremy** [android/storage#8]
<a href="https://github.com/commonsguy"><img src="https://avatars0.githubusercontent.com/u/103772?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [commonsguy](https://github.com/commonsguy)**
_Sunday Apr 14, 2019 at 19:41 GMT_
_Originally opened as https://github.com/googlesamples/android-SharingShortcuts/issues/2_

----

Steps to Reproduce:

- Clone the repo
- Attempt to build the app

Expected Results: for the app to build

Actual Results: the app fails with compile errors on references to `Intent.EXTRA_SHORTCUT_ID`, as [that is new to Android Q](https://developer.android.com/reference/android/content/Intent?hl=en#EXTRA_SHORTCUT_ID) but the `Application` module's `compileSdkVersion` is 28

Workaround: change `Application/build.gradle` to use `compileSdkVersion 'android-Q'`

**Comment by nic0lette** [comment]
I think this was addressed and fixed in the other repo (but wasn't closed). Let me know if this is still an issue.
